### ISSUE TITLE
Icon and multiple links

### ISSUE THREAD

**Issue by Orriky** [nimaaskarian/nitab#9] opened 2022-12-08 10:38 UTC
Hi,

Is it possible create a icon that open multiple links in multiple tabs?

Thanks

**Comment by nimaaskarian** [comment] 2022-12-21 08:39
Hey. 
Not in the taskbar, but you can use commands to do that.
`/command name firstlink secondlink`
I'm gonna add the ability to use commands within the taskbar icons. I'll let you know!
Are you using firefox?
Sorry for the late answer btw, I'm too busy these days.

**Comment by nimaaskarian** [comment] 2022-12-21 12:46
Hey. I added the ability to use commands in taskbar icon's urls in develop's [latest commit](https://github.com/nimaaskarian/nitab/commit/b3c0d110079ae9e37ca69a74c34f21501974f6bc). You can define a multi-url command using the example in the above comment, then simply type `name` in taskbar icon's url section. you can also pass arguments and stuff.
If you use firefox, wait for an update.

**Comment by Orriky** [comment] 2022-12-22 11:30
Thanks!!!
I don't know how to compile the extension, so I have to wait for the official release.
I also use Firefox.

**Comment by nimaaskarian** [comment] 2022-12-23 10:39
Hey again.
The new 4.1.9 release has been approved in Mozilla Addons. I tested it, and it seems fine. 
Note that firefox isn't my daily driver anymore, the code base is pretty much  the same with chromium but I can't test for bugs like before anymore, so if you came across some bugs I would be glad to fix the problems if you let me know they exist.
And I also would be happy to add more cool features like this that you suggest. 
If you tested it and seemed fine to you, you can close the issue to let me know it's fine for you.

**Comment by Orriky** [comment] 2022-12-23 16:32
Hi,
Thanks
The first icon works well, unfortunately the other icons open the same links of the first icon

**Comment by nimaaskarian** [comment] 2022-12-23 19:33
Can you include the file that `/exp` command gives you? because the same thing isn't happening for me. (be careful about your weather location info)

**Comment by Orriky** [comment] 2022-12-23 20:49
[exported-data_20221123202537.zip](https://github.com/nimaaskarian/nitab/files/10297284/exported-data_20221123202537.zip)

**Comment by nimaaskarian** [comment] 2022-12-24 12:13
Hey.
do `/command icon1 www.google.it www.repubblica.it`, then do `/command icon2 github.com/xiaoxiaoflood/firefox-scripts github.com/Aris-t2/CustomCSSforFx/releases github.com/Aris-t2/CustomJSforFx github.com/Endor8/userChrome.js github.com/alice0775/userChrome.js github.com/aminomancer/uc.css.js github.com/MrOtherGuy/firefox-csshacks www.reddit.com/r/firefox/new/ www.reddit.com/r/FirefoxCSS/new/ www.reddit.com/r/FirefoxCSS/ github.com/benzBrake/FirefoxCustomize www.reddit.com/r/startpages/ addons.mozilla.org/en-US/firefox/addon/nitab/ www.deviantart.com/sinine88/art/Sweet-Silence-176496049 www.reddit.com/r/FirefoxCSS/comments/zm9byl/photon_australis_tabs_messed_up_in_firefox_108/ www.cb01.in/wag-the-dog-sesso-potere/`.
Then set `icon1` for the first icon's url, and the `icon2` for the second icon.

**Comment by nimaaskarian** [comment] 2022-12-24 12:27
let me demonstrate the cause of your issue so you can better understand how taskbar in new update works.
![namecommand](https://user-images.githubusercontent.com/88832088/209436035-858c3565-c49c-4ad7-87f3-4f02b4f4aa22.png)
You have the command `name` set to `google.it` and `wikipedia.it` (as www isn't necessary to type in nitab); so if you type `/name` in Nitab's terminal, it will open `http://google.it` and `http://wikipedia.it` in two different tabs. This command doesn't support inputs, as you didn't use `%input%` anywhere when you defined it, so it will ignore anything you put infront of it. Simply typing `/name` won't be any different than `/name idk some input and arguments or urls like https://wiki.archlinux.org/`. Thats what clicking on that taskbar icon does, runs the command named `name` with the arguments that you put infront of it. You put command `name` in both icons, but with different arguments. Since this command ignores the arguments, the result will be same in both icons; leading to result you see, that Nitab opens `http://google.it` and `https://wikipedia.it` in both cases.

**Comment by Orriky** [comment] 2022-12-24 14:52
Hi,

Thanks!!! 
Apologize, I didn't have understood how to use your extension. Your explanation solved any issue.

**Closed as completed** 2022-12-24 14:54 UTC

**Comment by nimaaskarian** [comment] 2022-12-24 16:08
No need for apologizing, My extension is a bit obscure ngl, but I'm glad I could help!
I also will be happy if you give more suggestions and ask any issues you have and by this, help this extension grow.
Have a good one!
